name = "Faucet"
author = "IAmPetey"
version = "1.19.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1c6878263ef45182efca559ba6d71c645dbfa8806d6c91c5e85d8c0df8ec6ab1"

[versions]
forge = "43.2.0"
minecraft = "1.19.2"
