name = "Faucet"
author = "IAmPetey"
version = "1.19.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7aca9551852c709acd1ca85d5910e5865f5560a070bc304d89652a78732504a2"

[versions]
forge = "43.2.0"
minecraft = "1.19.2"
