name = "Faucet"
author = "IAmPetey"
version = "1.19.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a8f5ab8ef262005e0e2dc2ddf5b6d8ef62b6ed67576aeee5aa6676f5772c85ea"

[versions]
forge = "43.2.0"
minecraft = "1.19.2"
