name = "Faucet"
author = "IAmPetey"
version = "1.19.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1012489beeb07a90fd0b8a7676ce06199b599beca6a56009df8b4acc5f59091b"

[versions]
forge = "43.2.0"
minecraft = "1.19.2"
