name = "Faucet"
author = "IAmPetey"
version = "1.19.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f6491b30323cd071dd2af5caf3ba1d6364a1647132eaaa0447fc3040d32698b7"

[versions]
forge = "43.2.0"
minecraft = "1.19.2"
