name = "Faucet"
author = "IAmPetey"
version = "1.19.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "560965e23edf2abec1feff3ca3581f17a6e4aef9d11b55c77f3d87b1bafe81e2"

[versions]
forge = "43.2.0"
minecraft = "1.19.2"
