name = "Faucet"
author = "IAmPetey"
version = "1.19.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ee54abd9e1134da9954640b1ffd584e61d8c14bab38edac0df0ddebdbdaf6a78"

[versions]
forge = "43.2.0"
minecraft = "1.19.2"
