name = "Faucet"
author = "IAmPetey"
version = "1.19.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "286047d980edaca9d6150b020f4d1e77f0e99ae3a32c6d9d4328ca9a0a2fce10"

[versions]
forge = "43.2.0"
minecraft = "1.19.2"
