
[types]

	[types.leaves_type]

		[types.leaves_type.hexerei]
			mahogany = true
			willow = true
			witch_hazel = true

		[types.leaves_type.vinery]
			grapevine = true
			cherry = true
			apple = true

		[types.leaves_type.culturaldelights]
			avocado = true
			fruiting_avocado = true

		[types.leaves_type.environmental]
			willow = true
			cherry = true

		[types.leaves_type.upgrade_aquatic]
			river = true

		[types.leaves_type.atmospheric]
			rosewood = true
			morado = true
			flowering_morado = true
			yucca = true
			kousa = true
			aspen = true
			grimwood = true

		[types.leaves_type.ecologics]
			coconut = true
			walnut = true

		[types.leaves_type.autumnity]
			maple = true
			yellow_maple = true
			orange_maple = true
			red_maple = true

		[types.leaves_type.quark]
			blue_blossom = true
			lavender_blossom = true
			orange_blossom = true
			pink_blossom = true
			yellow_blossom = true
			red_blossom = true
			ancient = true

		[types.leaves_type.forbidden_arcanus]
			cherry = true
			aurum = true
			nuggety_aurum = true

		[types.leaves_type.windswept]
			holly = true
			chestnut = true

		[types.leaves_type.nethers_exoticism]
			jaboticaba = true

		[types.leaves_type.architects_palette]
			twisted = true

		[types.leaves_type.ars_nouveau]
			blue_archwood = true
			green_archwood = true
			purple_archwood = true
			red_archwood = true

		[types.leaves_type.twilightforest]
			beanstalk = true
			thorn = true
			twilight_oak = true
			canopy = true
			mangrove = true
			dark = true
			rainbow_oak = true
			time = true
			transformation = true
			mining = true
			sorting = true

		[types.leaves_type.occultism]
			otherworld = true

		[types.leaves_type.ad_astra]
			glacian = true

		[types.leaves_type.undergarden]
			smogstem = true
			wigglewood = true
			grongle = true

		[types.leaves_type.hexcasting]
			amethyst_edified = true
			aventurine_edified = true
			citrine_edified = true

		[types.leaves_type.ars_elemental]
			yellow_archwood = true

		[types.leaves_type.naturesaura]
			ancient = true
			golden = true

		[types.leaves_type.totemic]
			cedar = true

		[types.leaves_type.colorfulazaleas]
			blue_azalea = true
			blue_blooming_azalea = true
			blue_flowering_azalea = true
			orange_azalea = true
			orange_blooming_azalea = true
			orange_flowering_azalea = true
			pink_azalea = true
			pink_blooming_azalea = true
			pink_flowering_azalea = true
			purple_azalea = true
			purple_blooming_azalea = true
			purple_flowering_azalea = true
			red_azalea = true
			red_blooming_azalea = true
			red_flowering_azalea = true
			white_azalea = true
			white_blooming_azalea = true
			white_flowering_azalea = true
			yellow_azalea = true
			yellow_blooming_azalea = true
			yellow_flowering_azalea = true

		[types.leaves_type.solarcraft]
			ash = true
			runic = true
			radiant = true

		[types.leaves_type.twilightdelight]
			ironwood = true

		[types.leaves_type.primalmagick]
			hallowood = true

	[types.wood_type]

		[types.wood_type.darkerdepths]
			petrified = true

		[types.wood_type.quark]
			bamboo = true
			azalea = true
			blossom = true
			ancient = true

		[types.wood_type.ecologics]
			flowering_azalea = true
			azalea = true
			coconut = true
			walnut = true

		[types.wood_type.hexerei]
			mahogany = true
			willow = true
			witch_hazel = true

		[types.wood_type.vinery]
			cherry = true

		[types.wood_type.extendedmushrooms]
			mushroom = true
			glowshroom = true
			poisonous_mushroom = true
			honey_fungus = true

		[types.wood_type.environmental]
			willow = true
			cherry = true
			wisteria = true

		[types.wood_type.upgrade_aquatic]
			driftwood = true
			river = true

		[types.wood_type.atmospheric]
			rosewood = true
			morado = true
			yucca = true
			kousa = true
			aspen = true
			grimwood = true

		[types.wood_type.autumnity]
			maple = true

		[types.wood_type.forbidden_arcanus]
			fungyss = true
			cherry = true
			aurum = true
			edelwood = true

		[types.wood_type.windswept]
			holly = true
			chestnut = true

		[types.wood_type.nethers_exoticism]
			jabuticaba = true
			ramboutan = true

		[types.wood_type.architects_palette]
			twisted = true

		[types.wood_type.ars_nouveau]
			archwood = true

		[types.wood_type.ad_astra]
			aeronos = true
			strophar = true
			glacian = true

		[types.wood_type.twilightforest]
			twilight_oak = true
			canopy = true
			mangrove = true
			dark = true
			time = true
			transformation = true
			mining = true
			sorting = true

		[types.wood_type.undergarden]
			smogstem = true
			wigglewood = true
			grongle = true

		[types.wood_type.hexcasting]
			edified = true

		[types.wood_type.botania]
			livingwood = true
			dreamwood = true

		[types.wood_type.naturesaura]
			ancient = true

		[types.wood_type.totemic]
			cedar = true

		[types.wood_type.colorfulazaleas]
			tecal_azalea = true
			fiss_azalea = true
			roze_azalea = true
			azule_azalea = true
			bright_azalea = true
			walnut_azalea = true
			titanium_azalea = true

		[types.wood_type.solarcraft]
			runic = true
			radiant = true

		[types.wood_type.eidolon]
			illwood = true

		[types.wood_type.primalmagick]
			sunwood = true
			moonwood = true
			hallowood = true

[entries]

	[entries.leaves_type]

		[entries.leaves_type.quark]
			hedge = true
			leaf_carpet = true

	[entries.wood_type]

		[entries.wood_type.quark]
			vertical_planks = true
			post = true
			trapped_chest = true
			bookshelf = true
			chest = true
			stripped_post = true
			ladder = true
			hollow_log = true

		[entries.wood_type.another_furniture]
			table = true
			shelf = true
			drawer = true
			shutter = true
			planter_box = true
			bench = true
			chair = true

		[entries.wood_type.decorative_blocks]
			beam = true
			support = true
			seat = true
			palisade = true

		[entries.wood_type.create]
			window = true
			window_pane = true

		[entries.wood_type.farmersdelight]
			cabinet = true

		[entries.wood_type.backpacked]
			backpack_shelf = true

		[entries.wood_type.architects_palette]
			board_stairs = true
			railing = true
			board_slab = true
			boards = true
			board_wall = true

		[entries.wood_type.twilightforest]
			hollow_log_horizontal = true
			hollow_log_vertical = true
			banister = true
			hollow_log_climbable = true

